
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        name: Mypy Type Check
        exclude: 'tests/.*|docs/.*|scripts/.*|neo4j_runway/code_generation/generate_ingest.py'
        entry: mypy
        language: python
        types: [ python ]
        stages: [ commit, push ]
        args: [--strict, --ignore-missing-imports, --allow-subclassing-any, --allow-untyped-calls]
        additional_dependencies:
          - pytest
          - pydantic
          - types-PyYAML
  - repo: local
    hooks:
      - id: ruff-lint-isort
        name: Ruff Lint Sort Imports
        entry: poetry run ruff check --select I .
        language: system
        types: [ python ]
        stages: [ commit, push ]
      - id: ruff-lint
        name: Ruff Lint Check
        entry: poetry run ruff format --check
        language: system
        types: [ python ]
        stages: [ commit, push ]
